---
{
   "kind": "pipeline",
   "name": "default",
   "node_selector": {
      "drone": true
   },
   "steps": [
      {
         "commands": [
            "golangci-lint run -v --timeout 10m"
         ],
         "image": "golangci/golangci-lint:latest",
         "name": "Go lint",
         "pull": "always"
      },
      {
         "environment": {
            "DOCKER_BUILDKIT": 1
         },
         "image": "plugins/docker",
         "name": "Build container image",
         "pull": "always",
         "trigger": {
            "event": [
               "pull_request"
            ]
         },
         "when": {
            "branch": {
               "exclude": [
                  "master"
               ]
            }
         }
      },
      {
         "environment": {
            "DOCKER_BUILDKIT": 1
         },
         "image": "plugins/docker",
         "name": "Publish image kradalby/metallb-neighbour-helper",
         "pull": "always",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "kradalby/metallb-neighbour-helper",
            "tags": [
               "latest",
               "${DRONE_COMMIT_SHA:0:8}"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "image": "appleboy/drone-discord",
         "name": "Notify Discord",
         "pull": "always",
         "settings": {
            "message": "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}{{/success}}\n",
            "webhook_id": {
               "from_secret": "discord_webhook_id"
            },
            "webhook_token": {
               "from_secret": "discord_webhook_token"
            }
         },
         "when": {
            "status": [
               "success",
               "failure"
            ]
         }
      }
   ],
   "type": "kubernetes"
}
---
{
   "get": {
      "name": "id",
      "path": "discord-build"
   },
   "kind": "secret",
   "name": "discord_webhook_id"
}
---
{
   "get": {
      "name": "token",
      "path": "discord-build"
   },
   "kind": "secret",
   "name": "discord_webhook_token"
}
---
{
   "get": {
      "name": "username",
      "path": "docker"
   },
   "kind": "secret",
   "name": "docker_username"
}
---
{
   "get": {
      "name": "password",
      "path": "docker"
   },
   "kind": "secret",
   "name": "docker_password"
}
...
