---
{
  'kind': 'pipeline',
  'name': 'Kubernetes',
  'node_selector': { 'drone': true },
  'platform': { 'arch': 'amd64', 'os': 'linux' },
  'steps':
    [
      {
        'commands':
          [
            'npm install prettier',
            'echo .pre-commit-config.yaml >> .prettierignore',
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss,html,htm}"',
          ],
        'image': 'node:lts-buster',
        'name': 'Prettier lint',
        'pull': 'always',
      },
      {
        'commands':
          [
            'curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin',
            'golangci-lint run -v --timeout 10m',
          ],
        'image': 'golang:1.16-buster',
        'name': 'Go lint',
        'pull': 'always',
      },
      {
        'commands': ['go test ./...'],
        'image': 'golang:1.16-buster',
        'name': 'Go test',
        'pull': 'always',
      },
      {
        'environment': { 'DOCKER_BUILDKIT': 1 },
        'image': 'plugins/docker',
        'name': 'Build container image',
        'pull': 'always',
        'settings': { 'dry_run': true, 'purge': true, 'repo': 'build-only' },
        'trigger': { 'event': ['pull_request'] },
        'when': { 'branch': { 'exclude': ['master'] } },
      },
      {
        'environment': { 'DOCKER_BUILDKIT': 1 },
        'image': 'plugins/docker',
        'name': 'Publish image kradalby/metallb-neighbour-helper',
        'pull': 'always',
        'settings':
          {
            'password': { 'from_secret': 'docker_password' },
            'purge': true,
            'repo': 'kradalby/metallb-neighbour-helper',
            'tags':
              [
                'latest',
                'latest-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}',
                '${DRONE_COMMIT_SHA:0:8}',
              ],
            'username': { 'from_secret': 'docker_username' },
          },
        'when': { 'branch': ['master', 'main'], 'event': ['push'] },
      },
    ],
  'type': 'kubernetes',
}
