---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go/src
  path: github.com/kradalby/metallb-neighbour-helper

steps:
- name: lint
  pull: if-not-exists
  image: golang:1.12
  commands:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - golangci-lint --version
  - golangci-lint run --deadline 30m
  environment:
    GO111MODULE: on

- name: build
  # pull: if-not-exists
  pull: always
  image: banzaicloud/drone-kaniko
  settings:
    cache: false
    repo: kradalby/metallb-neighbour-helper
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: notify
  pull: if-not-exists
  image: drillster/drone-email
  settings:
    from: drone@drone.fap.no
    host: smtp.fap.no
    port: 25
    recipients:
    - kradalby@kradalby.no
    skip_verify: true
  when:
    status:
    - success
    - changed
    - failure
