apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metallb-helper.fullname" . }}
  labels:
{{ include "metallb-helper.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "metallb-helper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: metallb
      component: neighbour-helper
  template:
    metadata:
      labels:
        app: metallb
        component: neighbour-helper
        app.kubernetes.io/name: {{ include "metallb-helper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.metallb.serviceAccountName }}
      terminationGracePeriodSeconds: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --metallb-config={{ .Values.metallb.configmap }}
          - --metallb-helper-config={{ include "metallb-helper.fullname" . }}-config
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
